/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distribuida;

import javax.swing.*;
import java.rmi.Naming;

/**
 *
 * @author vsnv
 */
public class ClienteDePeaje extends javax.swing.JFrame {
    //Atributos de la clase ClienteDePeaje

    private boolean botonCierraCabinaCoches4Pulsado = false;
    private boolean botonCierraCabinaCoches5Pulsado = false;
    private boolean botonCierraCabinaCoches6Pulsado = false;
    private boolean botonCierraCabinaCamiones3Pulsado = false;
    private boolean botonCierraCabinaCamiones4Pulsado = false;

    //Método constructor
    public ClienteDePeaje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelPrincipal2 = new javax.swing.JPanel();
        JLabelEntradaPeaje2 = new javax.swing.JLabel();
        JTextFieldEntradaPeaje = new javax.swing.JTextField();
        panelCabinaCoches3 = new javax.swing.JPanel();
        labelCabinaCoches3 = new javax.swing.JLabel();
        labelVehiculoCabinaCoches3 = new javax.swing.JLabel();
        jTextFieldVehiculoCabinaCoche1 = new javax.swing.JTextField();
        labelEmpleadoCabinaCoche3 = new javax.swing.JLabel();
        jTextFieldEmpleadoCabinaCoche1 = new javax.swing.JTextField();
        panelCabinaCoches4 = new javax.swing.JPanel();
        jTextFieldVehiculoCabinaCoche2 = new javax.swing.JTextField();
        labelCabinaCoches4 = new javax.swing.JLabel();
        labelVehiculoCabinaCoches4 = new javax.swing.JLabel();
        labelEmpleadoCabinaCoche4 = new javax.swing.JLabel();
        jTextFieldEmpleadoCabinaCoche2 = new javax.swing.JTextField();
        panelCabinaCoche3 = new javax.swing.JPanel();
        jTextFieldVehiculoCabinaCoche3 = new javax.swing.JTextField();
        labelCabinaCoches5 = new javax.swing.JLabel();
        labelVehiculoCabinaCoches5 = new javax.swing.JLabel();
        labelEmpleadoCabinaCoche5 = new javax.swing.JLabel();
        jTextFieldEmpleadoCabinaCoche3 = new javax.swing.JTextField();
        panelCabinaCoches5 = new javax.swing.JPanel();
        labelCabinaCoches6 = new javax.swing.JLabel();
        labelVehiculoCabinaCoches6 = new javax.swing.JLabel();
        jTextFieldVehiculoCabinaCoche4 = new javax.swing.JTextField();
        botonCierraCabinaCoches4 = new javax.swing.JButton();
        panelCabinaCoches6 = new javax.swing.JPanel();
        labelVehiculoCabinaCoches7 = new javax.swing.JLabel();
        labelCabinaCoches7 = new javax.swing.JLabel();
        jTextFieldVehiculoCabinaCoche5 = new javax.swing.JTextField();
        botonCierraCabinaCoches5 = new javax.swing.JButton();
        panelCabinaCoches7 = new javax.swing.JPanel();
        labelCabinaCoches8 = new javax.swing.JLabel();
        labelVehiculoCabinaCoches8 = new javax.swing.JLabel();
        jTextFieldVehiculoCabinaCoche6 = new javax.swing.JTextField();
        botonCierraCabinaCoches6 = new javax.swing.JButton();
        panelCabinaCamiones1 = new javax.swing.JPanel();
        labelCabinaCamiones1 = new javax.swing.JLabel();
        labelVehiculoCabinaCamiones1 = new javax.swing.JLabel();
        labelEmpleadoCabinaCamiones1 = new javax.swing.JLabel();
        jTextFieldVehiculoCabinaCamiones1 = new javax.swing.JTextField();
        jTextFieldEmpleadoCabinaCamiones1 = new javax.swing.JTextField();
        panelCabinaCamiones2 = new javax.swing.JPanel();
        labelEmpleadoCabinaCamiones2 = new javax.swing.JLabel();
        jTextFieldVehiculoCabinaCamiones2 = new javax.swing.JTextField();
        labelCabinaCamiones2 = new javax.swing.JLabel();
        labelVehiculoCabinaCamiones2 = new javax.swing.JLabel();
        jTextFieldEmpleadoCabinaCamiones2 = new javax.swing.JTextField();
        panelCabinaCamiones3 = new javax.swing.JPanel();
        labelVehiculoCabinaCamiones3 = new javax.swing.JLabel();
        jTextFieldVehiculoCabinaCamiones3 = new javax.swing.JTextField();
        labelCabinaCamiones3 = new javax.swing.JLabel();
        botonCierraCabinaCamiones3 = new javax.swing.JButton();
        panelCabinaCamiones4 = new javax.swing.JPanel();
        labelVehiculoCabinaCamiones4 = new javax.swing.JLabel();
        labelCabinaCamiones4 = new javax.swing.JLabel();
        jTextFieldVehiculoCabinaCamiones4 = new javax.swing.JTextField();
        botonCierraCabinaCamiones4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelPrincipal2.setBackground(new java.awt.Color(204, 204, 204));
        JPanelPrincipal2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLabelEntradaPeaje2.setBackground(new java.awt.Color(255, 255, 255));
        JLabelEntradaPeaje2.setForeground(new java.awt.Color(0, 0, 0));
        JLabelEntradaPeaje2.setText("Vehículos esperando para entrar al peaje");
        JPanelPrincipal2.add(JLabelEntradaPeaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        JTextFieldEntradaPeaje.setBackground(new java.awt.Color(255, 255, 255));
        JTextFieldEntradaPeaje.setForeground(new java.awt.Color(0, 0, 0));
        JPanelPrincipal2.add(JTextFieldEntradaPeaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1200, 40));

        panelCabinaCoches3.setBackground(new java.awt.Color(153, 153, 153));
        panelCabinaCoches3.setForeground(new java.awt.Color(255, 255, 255));
        panelCabinaCoches3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCabinaCoches3.setForeground(new java.awt.Color(0, 0, 0));
        labelCabinaCoches3.setText("Cabina Coches 1 (manual)");
        panelCabinaCoches3.add(labelCabinaCoches3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        labelVehiculoCabinaCoches3.setBackground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches3.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches3.setText("Vehículo");
        panelCabinaCoches3.add(labelVehiculoCabinaCoches3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jTextFieldVehiculoCabinaCoche1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVehiculoCabinaCoche1.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCoches3.add(jTextFieldVehiculoCabinaCoche1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 190, 40));

        labelEmpleadoCabinaCoche3.setForeground(new java.awt.Color(0, 0, 0));
        labelEmpleadoCabinaCoche3.setText("Empleado");
        panelCabinaCoches3.add(labelEmpleadoCabinaCoche3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        jTextFieldEmpleadoCabinaCoche1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmpleadoCabinaCoche1.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCoches3.add(jTextFieldEmpleadoCabinaCoche1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 190, 40));

        JPanelPrincipal2.add(panelCabinaCoches3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 270, 160));

        panelCabinaCoches4.setBackground(new java.awt.Color(153, 153, 153));
        panelCabinaCoches4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldVehiculoCabinaCoche2.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVehiculoCabinaCoche2.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCoches4.add(jTextFieldVehiculoCabinaCoche2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 190, 40));

        labelCabinaCoches4.setForeground(new java.awt.Color(0, 0, 0));
        labelCabinaCoches4.setText("Cabina Coches 2 (manual)");
        panelCabinaCoches4.add(labelCabinaCoches4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        labelVehiculoCabinaCoches4.setBackground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches4.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches4.setText("Vehículo");
        panelCabinaCoches4.add(labelVehiculoCabinaCoches4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        labelEmpleadoCabinaCoche4.setForeground(new java.awt.Color(0, 0, 0));
        labelEmpleadoCabinaCoche4.setText("Empleado");
        panelCabinaCoches4.add(labelEmpleadoCabinaCoche4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jTextFieldEmpleadoCabinaCoche2.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmpleadoCabinaCoche2.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCoches4.add(jTextFieldEmpleadoCabinaCoche2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 190, 40));

        JPanelPrincipal2.add(panelCabinaCoches4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 280, 160));

        panelCabinaCoche3.setBackground(new java.awt.Color(153, 153, 153));
        panelCabinaCoche3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldVehiculoCabinaCoche3.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVehiculoCabinaCoche3.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCoche3.add(jTextFieldVehiculoCabinaCoche3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 190, 40));

        labelCabinaCoches5.setForeground(new java.awt.Color(0, 0, 0));
        labelCabinaCoches5.setText("Cabina Coches 3 (manual)");
        panelCabinaCoche3.add(labelCabinaCoches5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        labelVehiculoCabinaCoches5.setBackground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches5.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches5.setText("Vehículo");
        panelCabinaCoche3.add(labelVehiculoCabinaCoches5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        labelEmpleadoCabinaCoche5.setForeground(new java.awt.Color(0, 0, 0));
        labelEmpleadoCabinaCoche5.setText("Empleado");
        panelCabinaCoche3.add(labelEmpleadoCabinaCoche5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jTextFieldEmpleadoCabinaCoche3.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmpleadoCabinaCoche3.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCoche3.add(jTextFieldEmpleadoCabinaCoche3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 190, 40));

        JPanelPrincipal2.add(panelCabinaCoche3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 270, 160));

        panelCabinaCoches5.setBackground(new java.awt.Color(153, 153, 153));
        panelCabinaCoches5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCabinaCoches6.setForeground(new java.awt.Color(0, 0, 0));
        labelCabinaCoches6.setText("Cabina Coches 4 (automática)");
        panelCabinaCoches5.add(labelCabinaCoches6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        labelVehiculoCabinaCoches6.setBackground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches6.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches6.setText("Vehículo");
        panelCabinaCoches5.add(labelVehiculoCabinaCoches6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jTextFieldVehiculoCabinaCoche4.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVehiculoCabinaCoche4.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCoches5.add(jTextFieldVehiculoCabinaCoche4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 190, 40));

        botonCierraCabinaCoches4.setBackground(new java.awt.Color(0, 0, 0));
        botonCierraCabinaCoches4.setForeground(new java.awt.Color(255, 255, 255));
        botonCierraCabinaCoches4.setText("Cerrar");
        botonCierraCabinaCoches4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCierraCabinaCoches4ActionPerformed(evt);
            }
        });
        panelCabinaCoches5.add(botonCierraCabinaCoches4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 150, 30));

        JPanelPrincipal2.add(panelCabinaCoches5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 270, 140));

        panelCabinaCoches6.setBackground(new java.awt.Color(153, 153, 153));
        panelCabinaCoches6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelVehiculoCabinaCoches7.setBackground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches7.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches7.setText("Vehículo");
        panelCabinaCoches6.add(labelVehiculoCabinaCoches7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        labelCabinaCoches7.setForeground(new java.awt.Color(0, 0, 0));
        labelCabinaCoches7.setText("Cabina Coches 5 (automática)");
        panelCabinaCoches6.add(labelCabinaCoches7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jTextFieldVehiculoCabinaCoche5.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVehiculoCabinaCoche5.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCoches6.add(jTextFieldVehiculoCabinaCoche5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 190, 40));

        botonCierraCabinaCoches5.setBackground(new java.awt.Color(0, 0, 0));
        botonCierraCabinaCoches5.setForeground(new java.awt.Color(255, 255, 255));
        botonCierraCabinaCoches5.setText("Cerrar");
        botonCierraCabinaCoches5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCierraCabinaCoches5ActionPerformed(evt);
            }
        });
        panelCabinaCoches6.add(botonCierraCabinaCoches5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 120, 30));

        JPanelPrincipal2.add(panelCabinaCoches6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 280, 140));

        panelCabinaCoches7.setBackground(new java.awt.Color(153, 153, 153));
        panelCabinaCoches7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCabinaCoches8.setForeground(new java.awt.Color(0, 0, 0));
        labelCabinaCoches8.setText("Cabina Coches 6 (automática)");
        panelCabinaCoches7.add(labelCabinaCoches8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        labelVehiculoCabinaCoches8.setBackground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches8.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches8.setText("Vehículo");
        panelCabinaCoches7.add(labelVehiculoCabinaCoches8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jTextFieldVehiculoCabinaCoche6.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVehiculoCabinaCoche6.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCoches7.add(jTextFieldVehiculoCabinaCoche6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 190, 40));

        botonCierraCabinaCoches6.setBackground(new java.awt.Color(0, 0, 0));
        botonCierraCabinaCoches6.setForeground(new java.awt.Color(255, 255, 255));
        botonCierraCabinaCoches6.setText("Cerrar");
        botonCierraCabinaCoches6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCierraCabinaCoches6ActionPerformed(evt);
            }
        });
        panelCabinaCoches7.add(botonCierraCabinaCoches6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 140, 30));

        JPanelPrincipal2.add(panelCabinaCoches7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 270, 140));

        panelCabinaCamiones1.setBackground(new java.awt.Color(153, 153, 153));
        panelCabinaCamiones1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCabinaCamiones1.setForeground(new java.awt.Color(0, 0, 0));
        labelCabinaCamiones1.setText("Cabina Camiones 1 (manual)");
        panelCabinaCamiones1.add(labelCabinaCamiones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        labelVehiculoCabinaCamiones1.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCamiones1.setText("Vehículo");
        panelCabinaCamiones1.add(labelVehiculoCabinaCamiones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        labelEmpleadoCabinaCamiones1.setBackground(new java.awt.Color(0, 0, 0));
        labelEmpleadoCabinaCamiones1.setForeground(new java.awt.Color(0, 0, 0));
        labelEmpleadoCabinaCamiones1.setText("Empleado");
        panelCabinaCamiones1.add(labelEmpleadoCabinaCamiones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jTextFieldVehiculoCabinaCamiones1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVehiculoCabinaCamiones1.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCamiones1.add(jTextFieldVehiculoCabinaCamiones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 210, 40));

        jTextFieldEmpleadoCabinaCamiones1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmpleadoCabinaCamiones1.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCamiones1.add(jTextFieldEmpleadoCabinaCamiones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 210, 40));

        JPanelPrincipal2.add(panelCabinaCamiones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 300, 160));

        panelCabinaCamiones2.setBackground(new java.awt.Color(153, 153, 153));
        panelCabinaCamiones2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelEmpleadoCabinaCamiones2.setBackground(new java.awt.Color(0, 0, 0));
        labelEmpleadoCabinaCamiones2.setForeground(new java.awt.Color(0, 0, 0));
        labelEmpleadoCabinaCamiones2.setText("Empleado");
        panelCabinaCamiones2.add(labelEmpleadoCabinaCamiones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jTextFieldVehiculoCabinaCamiones2.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVehiculoCabinaCamiones2.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCamiones2.add(jTextFieldVehiculoCabinaCamiones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 200, 40));

        labelCabinaCamiones2.setForeground(new java.awt.Color(0, 0, 0));
        labelCabinaCamiones2.setText("Cabina Camiones 2 (manual)");
        panelCabinaCamiones2.add(labelCabinaCamiones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        labelVehiculoCabinaCamiones2.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCamiones2.setText("Vehículo");
        panelCabinaCamiones2.add(labelVehiculoCabinaCamiones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jTextFieldEmpleadoCabinaCamiones2.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmpleadoCabinaCamiones2.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCamiones2.add(jTextFieldEmpleadoCabinaCamiones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 200, 40));

        JPanelPrincipal2.add(panelCabinaCamiones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 290, 160));

        panelCabinaCamiones3.setBackground(new java.awt.Color(153, 153, 153));
        panelCabinaCamiones3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelVehiculoCabinaCamiones3.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCamiones3.setText("Vehículo");
        panelCabinaCamiones3.add(labelVehiculoCabinaCamiones3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jTextFieldVehiculoCabinaCamiones3.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVehiculoCabinaCamiones3.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCamiones3.add(jTextFieldVehiculoCabinaCamiones3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 200, 40));

        labelCabinaCamiones3.setForeground(new java.awt.Color(0, 0, 0));
        labelCabinaCamiones3.setText("Cabina Camiones 3 (automática)");
        panelCabinaCamiones3.add(labelCabinaCamiones3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        botonCierraCabinaCamiones3.setBackground(new java.awt.Color(0, 0, 0));
        botonCierraCabinaCamiones3.setForeground(new java.awt.Color(255, 255, 255));
        botonCierraCabinaCamiones3.setText("Cerrar");
        botonCierraCabinaCamiones3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCierraCabinaCamiones3ActionPerformed(evt);
            }
        });
        panelCabinaCamiones3.add(botonCierraCabinaCamiones3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 160, 40));

        JPanelPrincipal2.add(panelCabinaCamiones3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 280, 160));

        panelCabinaCamiones4.setBackground(new java.awt.Color(153, 153, 153));
        panelCabinaCamiones4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelVehiculoCabinaCamiones4.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCamiones4.setText("Vehículo");
        panelCabinaCamiones4.add(labelVehiculoCabinaCamiones4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        labelCabinaCamiones4.setForeground(new java.awt.Color(0, 0, 0));
        labelCabinaCamiones4.setText("Cabina Camiones 4 (automática)");
        panelCabinaCamiones4.add(labelCabinaCamiones4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        jTextFieldVehiculoCabinaCamiones4.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVehiculoCabinaCamiones4.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCamiones4.add(jTextFieldVehiculoCabinaCamiones4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 200, 40));

        botonCierraCabinaCamiones4.setBackground(new java.awt.Color(0, 0, 0));
        botonCierraCabinaCamiones4.setForeground(new java.awt.Color(255, 255, 255));
        botonCierraCabinaCamiones4.setText("Cerrar");
        botonCierraCabinaCamiones4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCierraCabinaCamiones4ActionPerformed(evt);
            }
        });
        panelCabinaCamiones4.add(botonCierraCabinaCamiones4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 160, 40));

        JPanelPrincipal2.add(panelCabinaCamiones4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 410, 290, 160));

        getContentPane().add(JPanelPrincipal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1220, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void botonCierraCabinaCoches4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCierraCabinaCoches4ActionPerformed
        // TODO add your handling code here:
        try{
            InterfacePeaje obj = (InterfacePeaje) Naming.lookup("//127.0.0.1/ObjetoPeaje");
            if(!isBotonCierraCabinaCoches4Pulsado()){
                //Cierra la cabina
                obj.cierraCabinaCoche4();
                //Cambiamos el texto del boton
                getBotonCierraCabinaCoches4().setText("Abrir");
                //Cambiamos el booleano
                setBotonCierraCabinaCoches4Pulsado(true);
            }
            else{
                obj.abreCabinaCoche4();
                //Cambiamos el texto del boton
                getBotonCierraCabinaCoches4().setText("Cerrar");
                //Cambiamos el booleano
                setBotonCierraCabinaCoches4Pulsado(false);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonCierraCabinaCoches4ActionPerformed

    private void botonCierraCabinaCoches5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCierraCabinaCoches5ActionPerformed
        // TODO add your handling code here:
        try{
            InterfacePeaje obj = (InterfacePeaje) Naming.lookup("//127.0.0.1/ObjetoPeaje");
            if(!isBotonCierraCabinaCoches5Pulsado()){
                //Cierra la cabina
                obj.cierraCabinaCoche5();
                //Cambiamos el texto del boton
                getBotonCierraCabinaCoches5().setText("Abrir");
                //Cambiamos el booleano
                setBotonCierraCabinaCoches5Pulsado(true);
            }
            else{
                obj.abreCabinaCoche5();
                //Cambiamos el texto del boton
                getBotonCierraCabinaCoches5().setText("Cerrar");
                //Cambiamos el booleano
                setBotonCierraCabinaCoches5Pulsado(false);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonCierraCabinaCoches5ActionPerformed

    private void botonCierraCabinaCoches6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCierraCabinaCoches6ActionPerformed
        // TODO add your handling code here:
        try{
            InterfacePeaje obj = (InterfacePeaje) Naming.lookup("//127.0.0.1/ObjetoPeaje");
            if(!isBotonCierraCabinaCoches6Pulsado()){
                //Cierra la cabina
                obj.cierraCabinaCoche6();
                //Cambiamos el texto del boton
                getBotonCierraCabinaCoches6().setText("Abrir");
                //Cambiamos el booleano
                setBotonCierraCabinaCoches6Pulsado(true);
            }
            else{
                obj.abreCabinaCoche6();
                //Cambiamos el texto del boton
                getBotonCierraCabinaCoches6().setText("Cerrar");
                //Cambiamos el booleano
                setBotonCierraCabinaCoches6Pulsado(false);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonCierraCabinaCoches6ActionPerformed

    private void botonCierraCabinaCamiones3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCierraCabinaCamiones3ActionPerformed
        // TODO add your handling code here:
        try{
            InterfacePeaje obj = (InterfacePeaje) Naming.lookup("//127.0.0.1/ObjetoPeaje");
            if(!isBotonCierraCabinaCamiones3Pulsado()){
                //Cierra la cabina
                obj.cierraCabinaCamion3();
                //Cambiamos el texto del boton
                getBotonCierraCabinaCamiones3().setText("Abrir");
                //Cambiamos el booleano
                setBotonCierraCabinaCamiones3Pulsado(true);
            }
            else{
                obj.abreCabinaCamion3();
                //Cambiamos el texto del boton
                getBotonCierraCabinaCamiones3().setText("Cerrar");
                //Cambiamos el booleano
                setBotonCierraCabinaCamiones3Pulsado(false);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonCierraCabinaCamiones3ActionPerformed

    private void botonCierraCabinaCamiones4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCierraCabinaCamiones4ActionPerformed
        // TODO add your handling code here:
        try{
            InterfacePeaje obj = (InterfacePeaje) Naming.lookup("//127.0.0.1/ObjetoPeaje");
            if(!isBotonCierraCabinaCamiones4Pulsado()){
                //Cierra la cabina
                obj.cierraCabinaCamion4();
                //Cambiamos el texto del boton
                getBotonCierraCabinaCamiones4().setText("Abrir");
                //Cambiamos el booleano
                setBotonCierraCabinaCamiones4Pulsado(true);
            }
            else{
                obj.abreCabinaCamion4();
                //Cambiamos el texto del boton
                getBotonCierraCabinaCamiones4().setText("Cerrar");
                //Cambiamos el booleano
                setBotonCierraCabinaCamiones4Pulsado(false);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonCierraCabinaCamiones4ActionPerformed

    //Actualiza los JTextField del cliente

    public void actualizaCuadrosDeTexto(){
        try{
            InterfacePeaje obj = (InterfacePeaje) Naming.lookup("//127.0.0.1/ObjetoPeaje");
            getJTextFieldEntradaPeaje().setText(obj.devuelveContenidoJTextFields("colaDeEsperaPeaje"));
            getjTextFieldVehiculoCabinaCoche1().setText(obj.devuelveContenidoJTextFields("vehiculoCabinaCoche1"));
            getjTextFieldVehiculoCabinaCoche2().setText(obj.devuelveContenidoJTextFields("vehiculoCabinaCoche2"));
            getjTextFieldVehiculoCabinaCoche3().setText(obj.devuelveContenidoJTextFields("vehiculoCabinaCoche3"));
            getjTextFieldVehiculoCabinaCoche4().setText(obj.devuelveContenidoJTextFields("vehiculoCabinaCoche4"));
            getjTextFieldVehiculoCabinaCoche5().setText(obj.devuelveContenidoJTextFields("vehiculoCabinaCoche5"));
            getjTextFieldVehiculoCabinaCoche6().setText(obj.devuelveContenidoJTextFields("vehiculoCabinaCoche6"));
            getjTextFieldVehiculoCabinaCamiones1().setText(obj.devuelveContenidoJTextFields("vehiculoCabinaCamion1"));
            getjTextFieldVehiculoCabinaCamiones2().setText(obj.devuelveContenidoJTextFields("vehiculoCabinaCamion2"));
            getjTextFieldVehiculoCabinaCamiones3().setText(obj.devuelveContenidoJTextFields("vehiculoCabinaCamion3"));
            getjTextFieldVehiculoCabinaCamiones4().setText(obj.devuelveContenidoJTextFields("vehiculoCabinaCamion4"));
            getjTextFieldEmpleadoCabinaCoche1().setText(obj.devuelveContenidoJTextFields("empleadoCabinaCoche1"));
            getjTextFieldEmpleadoCabinaCoche2().setText(obj.devuelveContenidoJTextFields("empleadoCabinaCoche2"));
            getjTextFieldEmpleadoCabinaCoche3().setText(obj.devuelveContenidoJTextFields("empleadoCabinaCoche3"));
            getjTextFieldEmpleadoCabinaCamiones1().setText(obj.devuelveContenidoJTextFields("empleadoCabinaCamion1"));
            getjTextFieldEmpleadoCabinaCamiones2().setText(obj.devuelveContenidoJTextFields("empleadoCabinaCamion2"));
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ClienteDePeaje cliente = new ClienteDePeaje();

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteDePeaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteDePeaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteDePeaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteDePeaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //ClienteDePeaje cliente = new ClienteDePeaje();
                cliente.setVisible(true);
            }
        });
        while(true){
            cliente.actualizaCuadrosDeTexto();
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ie) {
                ie.printStackTrace();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelEntradaPeaje2;
    private javax.swing.JPanel JPanelPrincipal2;
    private javax.swing.JTextField JTextFieldEntradaPeaje;
    private javax.swing.JButton botonCierraCabinaCamiones3;
    private javax.swing.JButton botonCierraCabinaCamiones4;
    private javax.swing.JButton botonCierraCabinaCoches4;
    private javax.swing.JButton botonCierraCabinaCoches5;
    private javax.swing.JButton botonCierraCabinaCoches6;
    private javax.swing.JTextField jTextFieldEmpleadoCabinaCamiones1;
    private javax.swing.JTextField jTextFieldEmpleadoCabinaCamiones2;
    private javax.swing.JTextField jTextFieldEmpleadoCabinaCoche1;
    private javax.swing.JTextField jTextFieldEmpleadoCabinaCoche2;
    private javax.swing.JTextField jTextFieldEmpleadoCabinaCoche3;
    private javax.swing.JTextField jTextFieldVehiculoCabinaCamiones1;
    private javax.swing.JTextField jTextFieldVehiculoCabinaCamiones2;
    private javax.swing.JTextField jTextFieldVehiculoCabinaCamiones3;
    private javax.swing.JTextField jTextFieldVehiculoCabinaCamiones4;
    private javax.swing.JTextField jTextFieldVehiculoCabinaCoche1;
    private javax.swing.JTextField jTextFieldVehiculoCabinaCoche2;
    private javax.swing.JTextField jTextFieldVehiculoCabinaCoche3;
    private javax.swing.JTextField jTextFieldVehiculoCabinaCoche4;
    private javax.swing.JTextField jTextFieldVehiculoCabinaCoche5;
    private javax.swing.JTextField jTextFieldVehiculoCabinaCoche6;
    private javax.swing.JLabel labelCabinaCamiones1;
    private javax.swing.JLabel labelCabinaCamiones2;
    private javax.swing.JLabel labelCabinaCamiones3;
    private javax.swing.JLabel labelCabinaCamiones4;
    private javax.swing.JLabel labelCabinaCoches3;
    private javax.swing.JLabel labelCabinaCoches4;
    private javax.swing.JLabel labelCabinaCoches5;
    private javax.swing.JLabel labelCabinaCoches6;
    private javax.swing.JLabel labelCabinaCoches7;
    private javax.swing.JLabel labelCabinaCoches8;
    private javax.swing.JLabel labelEmpleadoCabinaCamiones1;
    private javax.swing.JLabel labelEmpleadoCabinaCamiones2;
    private javax.swing.JLabel labelEmpleadoCabinaCoche3;
    private javax.swing.JLabel labelEmpleadoCabinaCoche4;
    private javax.swing.JLabel labelEmpleadoCabinaCoche5;
    private javax.swing.JLabel labelVehiculoCabinaCamiones1;
    private javax.swing.JLabel labelVehiculoCabinaCamiones2;
    private javax.swing.JLabel labelVehiculoCabinaCamiones3;
    private javax.swing.JLabel labelVehiculoCabinaCamiones4;
    private javax.swing.JLabel labelVehiculoCabinaCoches3;
    private javax.swing.JLabel labelVehiculoCabinaCoches4;
    private javax.swing.JLabel labelVehiculoCabinaCoches5;
    private javax.swing.JLabel labelVehiculoCabinaCoches6;
    private javax.swing.JLabel labelVehiculoCabinaCoches7;
    private javax.swing.JLabel labelVehiculoCabinaCoches8;
    private javax.swing.JPanel panelCabinaCamiones1;
    private javax.swing.JPanel panelCabinaCamiones2;
    private javax.swing.JPanel panelCabinaCamiones3;
    private javax.swing.JPanel panelCabinaCamiones4;
    private javax.swing.JPanel panelCabinaCoche3;
    private javax.swing.JPanel panelCabinaCoches3;
    private javax.swing.JPanel panelCabinaCoches4;
    private javax.swing.JPanel panelCabinaCoches5;
    private javax.swing.JPanel panelCabinaCoches6;
    private javax.swing.JPanel panelCabinaCoches7;
    // End of variables declaration//GEN-END:variables

    public boolean isBotonCierraCabinaCoches4Pulsado() {
        return botonCierraCabinaCoches4Pulsado;
    }

    public void setBotonCierraCabinaCoches4Pulsado(boolean botonCierraCabinaCoches4Pulsado) {
        this.botonCierraCabinaCoches4Pulsado = botonCierraCabinaCoches4Pulsado;
    }

    public boolean isBotonCierraCabinaCoches5Pulsado() {
        return botonCierraCabinaCoches5Pulsado;
    }

    public void setBotonCierraCabinaCoches5Pulsado(boolean botonCierraCabinaCoches5Pulsado) {
        this.botonCierraCabinaCoches5Pulsado = botonCierraCabinaCoches5Pulsado;
    }

    public boolean isBotonCierraCabinaCoches6Pulsado() {
        return botonCierraCabinaCoches6Pulsado;
    }

    public void setBotonCierraCabinaCoches6Pulsado(boolean botonCierraCabinaCoches6Pulsado) {
        this.botonCierraCabinaCoches6Pulsado = botonCierraCabinaCoches6Pulsado;
    }

    public boolean isBotonCierraCabinaCamiones3Pulsado() {
        return botonCierraCabinaCamiones3Pulsado;
    }

    public void setBotonCierraCabinaCamiones3Pulsado(boolean botonCierraCabinaCamiones3Pulsado) {
        this.botonCierraCabinaCamiones3Pulsado = botonCierraCabinaCamiones3Pulsado;
    }

    public boolean isBotonCierraCabinaCamiones4Pulsado() {
        return botonCierraCabinaCamiones4Pulsado;
    }

    public void setBotonCierraCabinaCamiones4Pulsado(boolean botonCierraCabinaCamiones4Pulsado) {
        this.botonCierraCabinaCamiones4Pulsado = botonCierraCabinaCamiones4Pulsado;
    }

    public JButton getBotonCierraCabinaCoches5() {
        return botonCierraCabinaCoches5;
    }

    public JButton getBotonCierraCabinaCamiones3() {
        return botonCierraCabinaCamiones3;
    }

    public JButton getBotonCierraCabinaCamiones4() {
        return botonCierraCabinaCamiones4;
    }

    public JButton getBotonCierraCabinaCoches4() {
        return botonCierraCabinaCoches4;
    }

    public JButton getBotonCierraCabinaCoches6() {
        return botonCierraCabinaCoches6;
    }

    public JTextField getJTextFieldEntradaPeaje() {
        return JTextFieldEntradaPeaje;
    }

    public JTextField getjTextFieldEmpleadoCabinaCamiones1() {
        return jTextFieldEmpleadoCabinaCamiones1;
    }

    public JTextField getjTextFieldEmpleadoCabinaCamiones2() {
        return jTextFieldEmpleadoCabinaCamiones2;
    }

    public JTextField getjTextFieldEmpleadoCabinaCoche1() {
        return jTextFieldEmpleadoCabinaCoche1;
    }

    public JTextField getjTextFieldEmpleadoCabinaCoche2() {
        return jTextFieldEmpleadoCabinaCoche2;
    }

    public JTextField getjTextFieldEmpleadoCabinaCoche3() {
        return jTextFieldEmpleadoCabinaCoche3;
    }

    public JTextField getjTextFieldVehiculoCabinaCamiones1() {
        return jTextFieldVehiculoCabinaCamiones1;
    }

    public JTextField getjTextFieldVehiculoCabinaCamiones2() {
        return jTextFieldVehiculoCabinaCamiones2;
    }

    public JTextField getjTextFieldVehiculoCabinaCamiones3() {
        return jTextFieldVehiculoCabinaCamiones3;
    }

    public JTextField getjTextFieldVehiculoCabinaCamiones4() {
        return jTextFieldVehiculoCabinaCamiones4;
    }

    public JTextField getjTextFieldVehiculoCabinaCoche1() {
        return jTextFieldVehiculoCabinaCoche1;
    }

    public JTextField getjTextFieldVehiculoCabinaCoche2() {
        return jTextFieldVehiculoCabinaCoche2;
    }

    public JTextField getjTextFieldVehiculoCabinaCoche3() {
        return jTextFieldVehiculoCabinaCoche3;
    }

    public JTextField getjTextFieldVehiculoCabinaCoche4() {
        return jTextFieldVehiculoCabinaCoche4;
    }

    public JTextField getjTextFieldVehiculoCabinaCoche5() {
        return jTextFieldVehiculoCabinaCoche5;
    }

    public JTextField getjTextFieldVehiculoCabinaCoche6() {
        return jTextFieldVehiculoCabinaCoche6;
    }
}
