package concurrencia;

import log.Log;

import javax.swing.*;

import distribuida.GestorInterface;
import java.rmi.Naming;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;

public class Servidor extends javax.swing.JFrame {
    private Peaje peaje;
    private Log archivoLog;
    private Paso paso;
    private boolean botonPulsado = false;
    private int numCoches = 0;
    private int numCamiones = 0;
    private int numAmbulancias = 0;


    public Servidor(){
        initComponents();
        int opcion = 0;
        //Creamos el log
        this.archivoLog = new Log(true);
        //Creamos el paso
        this.paso = new Paso();
        //Creamos el peaje
        this.peaje = new Peaje(getJTextFieldEntradaPeaje(),
                getjTextFieldEmpleadoCabinaCoche1(), getjTextFieldVehiculoCabinaCoche1(),
                getjTextFieldEmpleadoCabinaCoche2(), getjTextFieldVehiculoCabinaCoche2(),
                getjTextFieldEmpleadoCabinaCoche3(), getjTextFieldVehiculoCabinaCoche3(),
                getjTextFieldVehiculoCabinaCoche4(), getjTextFieldVehiculoCabinaCoche5(),
                getjTextFieldVehiculoCabinaCoche6(),
                getjTextFieldEmpleadoCabinaCamiones1(), getjTextFieldVehiculoCabinaCamiones1(),
                getjTextFieldEmpleadoCabinaCamiones2(), getjTextFieldVehiculoCabinaCamiones2(),
                getjTextFieldVehiculoCabinaCamiones3(), getjTextFieldVehiculoCabinaCamiones4(),
                getArchivoLog());
        //Creamos a los empleados
        for(int i = 0; i < 5; i++){
            Empleado empleado = new Empleado(getPeaje(), "Empleado", i, getPaso());
            empleado.start();
        }
        //Creamos a los vehículos
        for(int i = 0; i < 100; i++){
            //Elegimos el tipo del vehiculo al azar
            opcion = (int)(Math.random() * 2 + 1);
            switch (opcion){
                case 1:
                    //El vehículo será un coche
                    Vehiculo coche = new Vehiculo(getPeaje(), "Coche", getNumCoches(), getPaso());
                    coche.start();
                    setNumCoches(getNumCoches() + 1);
                    break;
                case 2:
                    //El vehículo será un camión
                    Vehiculo camion = new Vehiculo(getPeaje(), "Camion", getNumCamiones(), getPaso());
                    camion.start();
                    setNumCamiones(getNumCamiones() + 1);
                    break;
            }
        }
        //Inicializamos la conexión del RMI
        try{
            GestorInterface obj = new GestorInterface(getPeaje());
            Registry registry = LocateRegistry.createRegistry(1099);
            Naming.rebind("//localhost/ObjetoPeaje",obj);
            System.out.println("El Objeto Peaje ha quedado registrado");
            getArchivoLog().escribirEnLog("El objeto Peaje ha quedado registrado");
        }
        catch(Exception e) {
            System.out.println("Error: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelPrincipal = new javax.swing.JPanel();
        JLabelEntradaPeaje = new javax.swing.JLabel();
        JTextFieldEntradaPeaje = new javax.swing.JTextField();
        panelCabinaCoches1 = new javax.swing.JPanel();
        labelCabinaCoches1 = new javax.swing.JLabel();
        labelVehiculoCabinaCoches1 = new javax.swing.JLabel();
        jTextFieldVehiculoCabinaCoche1 = new javax.swing.JTextField();
        labelEmpleadoCabinaCoche1 = new javax.swing.JLabel();
        jTextFieldEmpleadoCabinaCoche1 = new javax.swing.JTextField();
        panelCabinaCoches2 = new javax.swing.JPanel();
        jTextFieldVehiculoCabinaCoche2 = new javax.swing.JTextField();
        jTextFieldEmpleadoCabinaCoche2 = new javax.swing.JTextField();
        labelCabinaCoches2 = new javax.swing.JLabel();
        labelVehiculoCabinaCoches2 = new javax.swing.JLabel();
        labelEmpleadoCabinaCoche2 = new javax.swing.JLabel();
        panelCabinaCoche3 = new javax.swing.JPanel();
        jTextFieldVehiculoCabinaCoche3 = new javax.swing.JTextField();
        jTextFieldEmpleadoCabinaCoche3 = new javax.swing.JTextField();
        labelCabinaCoches3 = new javax.swing.JLabel();
        labelVehiculoCabinaCoches3 = new javax.swing.JLabel();
        labelEmpleadoCabinaCoche3 = new javax.swing.JLabel();
        panelCabinaCoches4 = new javax.swing.JPanel();
        labelCabinaCoches4 = new javax.swing.JLabel();
        labelVehiculoCabinaCoches4 = new javax.swing.JLabel();
        jTextFieldVehiculoCabinaCoche4 = new javax.swing.JTextField();
        panelCabinaCoches5 = new javax.swing.JPanel();
        labelVehiculoCabinaCoches5 = new javax.swing.JLabel();
        labelCabinaCoches5 = new javax.swing.JLabel();
        jTextFieldVehiculoCabinaCoche5 = new javax.swing.JTextField();
        panelCabinaCoches6 = new javax.swing.JPanel();
        labelCabinaCoches6 = new javax.swing.JLabel();
        labelVehiculoCabinaCoches6 = new javax.swing.JLabel();
        jTextFieldVehiculoCabinaCoche6 = new javax.swing.JTextField();
        panelCabinaCamiones1 = new javax.swing.JPanel();
        labelCabinaCamiones1 = new javax.swing.JLabel();
        labelVehiculoCabinaCamiones1 = new javax.swing.JLabel();
        labelEmpleadoCabinaCamiones1 = new javax.swing.JLabel();
        jTextFieldVehiculoCabinaCamiones1 = new javax.swing.JTextField();
        jTextFieldEmpleadoCabinaCamiones1 = new javax.swing.JTextField();
        panelCabinaCamiones2 = new javax.swing.JPanel();
        labelEmpleadoCabinaCamiones2 = new javax.swing.JLabel();
        jTextFieldVehiculoCabinaCamiones2 = new javax.swing.JTextField();
        labelCabinaCamiones2 = new javax.swing.JLabel();
        labelVehiculoCabinaCamiones2 = new javax.swing.JLabel();
        jTextFieldEmpleadoCabinaCamiones2 = new javax.swing.JTextField();
        panelCabinaCamiones3 = new javax.swing.JPanel();
        labelVehiculoCabinaCamiones3 = new javax.swing.JLabel();
        jTextFieldVehiculoCabinaCamiones3 = new javax.swing.JTextField();
        labelCabinaCamiones3 = new javax.swing.JLabel();
        panelCabinaCamiones4 = new javax.swing.JPanel();
        labelVehiculoCabinaCamiones4 = new javax.swing.JLabel();
        labelCabinaCamiones4 = new javax.swing.JLabel();
        jTextFieldVehiculoCabinaCamiones4 = new javax.swing.JTextField();
        botonPararReanudar = new javax.swing.JButton();
        botonAmbulancia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        JPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLabelEntradaPeaje.setBackground(new java.awt.Color(255, 255, 255));
        JLabelEntradaPeaje.setForeground(new java.awt.Color(0, 0, 0));
        JLabelEntradaPeaje.setText("Vehículos esperando para entrar al peaje");
        JPanelPrincipal.add(JLabelEntradaPeaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        JTextFieldEntradaPeaje.setBackground(new java.awt.Color(255, 255, 255));
        JTextFieldEntradaPeaje.setForeground(new java.awt.Color(0, 0, 0));
        JPanelPrincipal.add(JTextFieldEntradaPeaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1200, 40));

        panelCabinaCoches1.setBackground(new java.awt.Color(153, 153, 153));
        panelCabinaCoches1.setForeground(new java.awt.Color(255, 255, 255));
        panelCabinaCoches1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCabinaCoches1.setForeground(new java.awt.Color(0, 0, 0));
        labelCabinaCoches1.setText("Cabina Coches 1 (manual)");
        panelCabinaCoches1.add(labelCabinaCoches1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        labelVehiculoCabinaCoches1.setBackground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches1.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches1.setText("Vehículo");
        panelCabinaCoches1.add(labelVehiculoCabinaCoches1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jTextFieldVehiculoCabinaCoche1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVehiculoCabinaCoche1.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCoches1.add(jTextFieldVehiculoCabinaCoche1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 190, 40));

        labelEmpleadoCabinaCoche1.setForeground(new java.awt.Color(0, 0, 0));
        labelEmpleadoCabinaCoche1.setText("Empleado");
        panelCabinaCoches1.add(labelEmpleadoCabinaCoche1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jTextFieldEmpleadoCabinaCoche1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmpleadoCabinaCoche1.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCoches1.add(jTextFieldEmpleadoCabinaCoche1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 190, 40));

        JPanelPrincipal.add(panelCabinaCoches1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 290, 160));

        panelCabinaCoches2.setBackground(new java.awt.Color(153, 153, 153));
        panelCabinaCoches2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldVehiculoCabinaCoche2.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVehiculoCabinaCoche2.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCoches2.add(jTextFieldVehiculoCabinaCoche2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 190, 40));

        jTextFieldEmpleadoCabinaCoche2.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmpleadoCabinaCoche2.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCoches2.add(jTextFieldEmpleadoCabinaCoche2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 190, 40));

        labelCabinaCoches2.setForeground(new java.awt.Color(0, 0, 0));
        labelCabinaCoches2.setText("Cabina Coches 2 (manual)");
        panelCabinaCoches2.add(labelCabinaCoches2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        labelVehiculoCabinaCoches2.setBackground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches2.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches2.setText("Vehículo");
        panelCabinaCoches2.add(labelVehiculoCabinaCoches2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        labelEmpleadoCabinaCoche2.setForeground(new java.awt.Color(0, 0, 0));
        labelEmpleadoCabinaCoche2.setText("Empleado");
        panelCabinaCoches2.add(labelEmpleadoCabinaCoche2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        JPanelPrincipal.add(panelCabinaCoches2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 290, 160));

        panelCabinaCoche3.setBackground(new java.awt.Color(153, 153, 153));
        panelCabinaCoche3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldVehiculoCabinaCoche3.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVehiculoCabinaCoche3.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCoche3.add(jTextFieldVehiculoCabinaCoche3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 190, 40));

        jTextFieldEmpleadoCabinaCoche3.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmpleadoCabinaCoche3.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCoche3.add(jTextFieldEmpleadoCabinaCoche3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 190, 40));

        labelCabinaCoches3.setForeground(new java.awt.Color(0, 0, 0));
        labelCabinaCoches3.setText("Cabina Coches 3 (manual)");
        panelCabinaCoche3.add(labelCabinaCoches3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        labelVehiculoCabinaCoches3.setBackground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches3.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches3.setText("Vehículo");
        panelCabinaCoche3.add(labelVehiculoCabinaCoches3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        labelEmpleadoCabinaCoche3.setForeground(new java.awt.Color(0, 0, 0));
        labelEmpleadoCabinaCoche3.setText("Empleado");
        panelCabinaCoche3.add(labelEmpleadoCabinaCoche3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        JPanelPrincipal.add(panelCabinaCoche3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 280, 160));

        panelCabinaCoches4.setBackground(new java.awt.Color(153, 153, 153));
        panelCabinaCoches4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCabinaCoches4.setForeground(new java.awt.Color(0, 0, 0));
        labelCabinaCoches4.setText("Cabina Coches 4 (automática)");
        panelCabinaCoches4.add(labelCabinaCoches4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        labelVehiculoCabinaCoches4.setBackground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches4.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches4.setText("Vehículo");
        panelCabinaCoches4.add(labelVehiculoCabinaCoches4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jTextFieldVehiculoCabinaCoche4.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVehiculoCabinaCoche4.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCoches4.add(jTextFieldVehiculoCabinaCoche4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 190, 40));

        JPanelPrincipal.add(panelCabinaCoches4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 290, 140));

        panelCabinaCoches5.setBackground(new java.awt.Color(153, 153, 153));
        panelCabinaCoches5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelVehiculoCabinaCoches5.setBackground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches5.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches5.setText("Vehículo");
        panelCabinaCoches5.add(labelVehiculoCabinaCoches5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        labelCabinaCoches5.setForeground(new java.awt.Color(0, 0, 0));
        labelCabinaCoches5.setText("Cabina Coches 5 (automática)");
        panelCabinaCoches5.add(labelCabinaCoches5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        jTextFieldVehiculoCabinaCoche5.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVehiculoCabinaCoche5.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCoches5.add(jTextFieldVehiculoCabinaCoche5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 190, 40));

        JPanelPrincipal.add(panelCabinaCoches5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 290, 140));

        panelCabinaCoches6.setBackground(new java.awt.Color(153, 153, 153));
        panelCabinaCoches6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCabinaCoches6.setForeground(new java.awt.Color(0, 0, 0));
        labelCabinaCoches6.setText("Cabina Coches 6 (automática)");
        panelCabinaCoches6.add(labelCabinaCoches6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        labelVehiculoCabinaCoches6.setBackground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches6.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCoches6.setText("Vehículo");
        panelCabinaCoches6.add(labelVehiculoCabinaCoches6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jTextFieldVehiculoCabinaCoche6.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVehiculoCabinaCoche6.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCoches6.add(jTextFieldVehiculoCabinaCoche6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 190, 40));

        JPanelPrincipal.add(panelCabinaCoches6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 280, 140));

        panelCabinaCamiones1.setBackground(new java.awt.Color(153, 153, 153));
        panelCabinaCamiones1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCabinaCamiones1.setForeground(new java.awt.Color(0, 0, 0));
        labelCabinaCamiones1.setText("Cabina Camiones 1 (manual)");
        panelCabinaCamiones1.add(labelCabinaCamiones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        labelVehiculoCabinaCamiones1.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCamiones1.setText("Vehículo");
        panelCabinaCamiones1.add(labelVehiculoCabinaCamiones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        labelEmpleadoCabinaCamiones1.setBackground(new java.awt.Color(0, 0, 0));
        labelEmpleadoCabinaCamiones1.setForeground(new java.awt.Color(0, 0, 0));
        labelEmpleadoCabinaCamiones1.setText("Empleado");
        panelCabinaCamiones1.add(labelEmpleadoCabinaCamiones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jTextFieldVehiculoCabinaCamiones1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVehiculoCabinaCamiones1.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCamiones1.add(jTextFieldVehiculoCabinaCamiones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 210, 40));

        jTextFieldEmpleadoCabinaCamiones1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmpleadoCabinaCamiones1.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCamiones1.add(jTextFieldEmpleadoCabinaCamiones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 210, 40));

        JPanelPrincipal.add(panelCabinaCamiones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 300, 160));

        panelCabinaCamiones2.setBackground(new java.awt.Color(153, 153, 153));
        panelCabinaCamiones2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelEmpleadoCabinaCamiones2.setBackground(new java.awt.Color(0, 0, 0));
        labelEmpleadoCabinaCamiones2.setForeground(new java.awt.Color(0, 0, 0));
        labelEmpleadoCabinaCamiones2.setText("Empleado");
        panelCabinaCamiones2.add(labelEmpleadoCabinaCamiones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jTextFieldVehiculoCabinaCamiones2.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVehiculoCabinaCamiones2.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCamiones2.add(jTextFieldVehiculoCabinaCamiones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 200, 40));

        labelCabinaCamiones2.setForeground(new java.awt.Color(0, 0, 0));
        labelCabinaCamiones2.setText("Cabina Camiones 2 (manual)");
        panelCabinaCamiones2.add(labelCabinaCamiones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        labelVehiculoCabinaCamiones2.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCamiones2.setText("Vehículo");
        panelCabinaCamiones2.add(labelVehiculoCabinaCamiones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jTextFieldEmpleadoCabinaCamiones2.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmpleadoCabinaCamiones2.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCamiones2.add(jTextFieldEmpleadoCabinaCamiones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 200, 40));

        JPanelPrincipal.add(panelCabinaCamiones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 290, 160));

        panelCabinaCamiones3.setBackground(new java.awt.Color(153, 153, 153));
        panelCabinaCamiones3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelVehiculoCabinaCamiones3.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCamiones3.setText("Vehículo");
        panelCabinaCamiones3.add(labelVehiculoCabinaCamiones3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jTextFieldVehiculoCabinaCamiones3.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVehiculoCabinaCamiones3.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCamiones3.add(jTextFieldVehiculoCabinaCamiones3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 200, 40));

        labelCabinaCamiones3.setForeground(new java.awt.Color(0, 0, 0));
        labelCabinaCamiones3.setText("Cabina Camiones 3 (automática)");
        panelCabinaCamiones3.add(labelCabinaCamiones3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        JPanelPrincipal.add(panelCabinaCamiones3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 280, 160));

        panelCabinaCamiones4.setBackground(new java.awt.Color(153, 153, 153));
        panelCabinaCamiones4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelVehiculoCabinaCamiones4.setForeground(new java.awt.Color(0, 0, 0));
        labelVehiculoCabinaCamiones4.setText("Vehículo");
        panelCabinaCamiones4.add(labelVehiculoCabinaCamiones4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        labelCabinaCamiones4.setForeground(new java.awt.Color(0, 0, 0));
        labelCabinaCamiones4.setText("Cabina Camiones 4 (automática)");
        panelCabinaCamiones4.add(labelCabinaCamiones4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        jTextFieldVehiculoCabinaCamiones4.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVehiculoCabinaCamiones4.setForeground(new java.awt.Color(0, 0, 0));
        panelCabinaCamiones4.add(jTextFieldVehiculoCabinaCamiones4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 200, 40));

        JPanelPrincipal.add(panelCabinaCamiones4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 440, 290, 160));

        botonPararReanudar.setBackground(new java.awt.Color(0, 0, 0));
        botonPararReanudar.setForeground(new java.awt.Color(255, 255, 255));
        botonPararReanudar.setText("Parar");
        botonPararReanudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPararReanudarActionPerformed(evt);
            }
        });
        JPanelPrincipal.add(botonPararReanudar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 620, 110, 40));

        botonAmbulancia.setBackground(new java.awt.Color(0, 0, 0));
        botonAmbulancia.setForeground(new java.awt.Color(255, 255, 255));
        botonAmbulancia.setText("Ambulancia");
        botonAmbulancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAmbulanciaActionPerformed(evt);
            }
        });
        JPanelPrincipal.add(botonAmbulancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 620, 120, 40));

        getContentPane().add(JPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1230, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPararReanudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPararReanudarActionPerformed
        // TODO add your handling code here:
        if(!isBotonPulsado()) //Si no se ha pulsado
        {
            setBotonPulsado(true); //Lo cambiamos a pulsado
            getBotonPararReanudar().setText("Reanudar"); //Cambiamos el texto
            getPaso().cerrar();//Cerramos el paso
        }
        else //Si ya se había pulsado
        {
            setBotonPulsado(false); //Lo cambiamos
            getBotonPararReanudar().setText("Parar"); //Cambiamos el texto
            getPaso().abrir(); //Abrimos el paso
        }
    }//GEN-LAST:event_botonPararReanudarActionPerformed

    private void botonAmbulanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAmbulanciaActionPerformed
        // TODO add your handling code here:
        //El numero total de ambulancias será el que haya en ese momento mas 1, ya que se va a crear una
        Vehiculo ambulancia = new Vehiculo(getPeaje(), "Ambulancia", getNumAmbulancias(), getPaso());
        setNumAmbulancias(getNumAmbulancias() + 1);
        ambulancia.start();
    }//GEN-LAST:event_botonAmbulanciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelEntradaPeaje;
    private javax.swing.JPanel JPanelPrincipal;
    private javax.swing.JTextField JTextFieldEntradaPeaje;
    private javax.swing.JButton botonAmbulancia;
    private javax.swing.JButton botonPararReanudar;
    private javax.swing.JTextField jTextFieldEmpleadoCabinaCamiones1;
    private javax.swing.JTextField jTextFieldEmpleadoCabinaCamiones2;
    private javax.swing.JTextField jTextFieldEmpleadoCabinaCoche1;
    private javax.swing.JTextField jTextFieldEmpleadoCabinaCoche2;
    private javax.swing.JTextField jTextFieldEmpleadoCabinaCoche3;
    private javax.swing.JTextField jTextFieldVehiculoCabinaCamiones1;
    private javax.swing.JTextField jTextFieldVehiculoCabinaCamiones2;
    private javax.swing.JTextField jTextFieldVehiculoCabinaCamiones3;
    private javax.swing.JTextField jTextFieldVehiculoCabinaCamiones4;
    private javax.swing.JTextField jTextFieldVehiculoCabinaCoche1;
    private javax.swing.JTextField jTextFieldVehiculoCabinaCoche2;
    private javax.swing.JTextField jTextFieldVehiculoCabinaCoche3;
    private javax.swing.JTextField jTextFieldVehiculoCabinaCoche4;
    private javax.swing.JTextField jTextFieldVehiculoCabinaCoche5;
    private javax.swing.JTextField jTextFieldVehiculoCabinaCoche6;
    private javax.swing.JLabel labelCabinaCamiones1;
    private javax.swing.JLabel labelCabinaCamiones2;
    private javax.swing.JLabel labelCabinaCamiones3;
    private javax.swing.JLabel labelCabinaCamiones4;
    private javax.swing.JLabel labelCabinaCoches1;
    private javax.swing.JLabel labelCabinaCoches2;
    private javax.swing.JLabel labelCabinaCoches3;
    private javax.swing.JLabel labelCabinaCoches4;
    private javax.swing.JLabel labelCabinaCoches5;
    private javax.swing.JLabel labelCabinaCoches6;
    private javax.swing.JLabel labelEmpleadoCabinaCamiones1;
    private javax.swing.JLabel labelEmpleadoCabinaCamiones2;
    private javax.swing.JLabel labelEmpleadoCabinaCoche1;
    private javax.swing.JLabel labelEmpleadoCabinaCoche2;
    private javax.swing.JLabel labelEmpleadoCabinaCoche3;
    private javax.swing.JLabel labelVehiculoCabinaCamiones1;
    private javax.swing.JLabel labelVehiculoCabinaCamiones2;
    private javax.swing.JLabel labelVehiculoCabinaCamiones3;
    private javax.swing.JLabel labelVehiculoCabinaCamiones4;
    private javax.swing.JLabel labelVehiculoCabinaCoches1;
    private javax.swing.JLabel labelVehiculoCabinaCoches2;
    private javax.swing.JLabel labelVehiculoCabinaCoches3;
    private javax.swing.JLabel labelVehiculoCabinaCoches4;
    private javax.swing.JLabel labelVehiculoCabinaCoches5;
    private javax.swing.JLabel labelVehiculoCabinaCoches6;
    private javax.swing.JPanel panelCabinaCamiones1;
    private javax.swing.JPanel panelCabinaCamiones2;
    private javax.swing.JPanel panelCabinaCamiones3;
    private javax.swing.JPanel panelCabinaCamiones4;
    private javax.swing.JPanel panelCabinaCoche3;
    private javax.swing.JPanel panelCabinaCoches1;
    private javax.swing.JPanel panelCabinaCoches2;
    private javax.swing.JPanel panelCabinaCoches4;
    private javax.swing.JPanel panelCabinaCoches5;
    private javax.swing.JPanel panelCabinaCoches6;
    // End of variables declaration//GEN-END:variables

    //Método get para el JTextFieldEntradaPeaje
    public JTextField getJTextFieldEntradaPeaje() {
        return JTextFieldEntradaPeaje;
    }

    public JTextField getjTextFieldEmpleadoCabinaCamiones1() {
        return jTextFieldEmpleadoCabinaCamiones1;
    }

    public JTextField getjTextFieldEmpleadoCabinaCamiones2() {
        return jTextFieldEmpleadoCabinaCamiones2;
    }

    public JTextField getjTextFieldEmpleadoCabinaCoche1() {
        return jTextFieldEmpleadoCabinaCoche1;
    }

    public JTextField getjTextFieldEmpleadoCabinaCoche2() {
        return jTextFieldEmpleadoCabinaCoche2;
    }

    public JTextField getjTextFieldEmpleadoCabinaCoche3() {
        return jTextFieldEmpleadoCabinaCoche3;
    }

    public JTextField getjTextFieldVehiculoCabinaCamiones1() {
        return jTextFieldVehiculoCabinaCamiones1;
    }

    public JTextField getjTextFieldVehiculoCabinaCamiones2() {
        return jTextFieldVehiculoCabinaCamiones2;
    }

    public JTextField getjTextFieldVehiculoCabinaCamiones3() {
        return jTextFieldVehiculoCabinaCamiones3;
    }

    public JTextField getjTextFieldVehiculoCabinaCamiones4() {
        return jTextFieldVehiculoCabinaCamiones4;
    }

    public JTextField getjTextFieldVehiculoCabinaCoche1() {
        return jTextFieldVehiculoCabinaCoche1;
    }

    public JTextField getjTextFieldVehiculoCabinaCoche2() {
        return jTextFieldVehiculoCabinaCoche2;
    }

    public JTextField getjTextFieldVehiculoCabinaCoche3() {
        return jTextFieldVehiculoCabinaCoche3;
    }

    public JTextField getjTextFieldVehiculoCabinaCoche4() {
        return jTextFieldVehiculoCabinaCoche4;
    }

    public JTextField getjTextFieldVehiculoCabinaCoche5() {
        return jTextFieldVehiculoCabinaCoche5;
    }

    public JTextField getjTextFieldVehiculoCabinaCoche6() {
        return jTextFieldVehiculoCabinaCoche6;
    }

    public Peaje getPeaje(){
        return peaje;
    }

    public Paso getPaso(){
        return paso;
    }

    public boolean isBotonPulsado() {
        return botonPulsado;
    }

    public void setBotonPulsado(boolean botonPulsado) {
        this.botonPulsado = botonPulsado;
    }

    public JButton getBotonPararReanudar() {
        return botonPararReanudar;
    }

    public int getNumCoches() {
        return numCoches;
    }

    public void setNumCoches(int numCoches) {
        this.numCoches = numCoches;
    }

    public int getNumCamiones() {
        return numCamiones;
    }

    public void setNumCamiones(int numCamiones) {
        this.numCamiones = numCamiones;
    }

    public int getNumAmbulancias() {
        return numAmbulancias;
    }

    public void setNumAmbulancias(int numAmbulancias) {
        this.numAmbulancias = numAmbulancias;
    }

    public Log getArchivoLog() {
        return archivoLog;
    }
}
